import { useState,useEffect } from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import http from '../http-common'
import { useAuth } from '../context/authContext';

export default function Home() {
    const { initialState,isAuthenticated } = useAuth();
    const [subscribers,setSubscribers] = useState([]);
   
    useEffect(() => {
          http.get('subscribers').then(response => {
              setSubscribers(response.data.data); 
          }).catch(()=> {
              console.clear()
          });
    },[]);

  const sub_list = subscribers.map(subscriber => 
    <tr key={subscriber.id}>
      <td>{subscriber.id}</td>
      <td>{subscriber.name}</td>
      <td>{subscriber.email}</td>
      <td>{subscriber.state}</td>
    </tr>
 );
  
  return (
    <div>
      <Head>
        <title>First Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        { isAuthenticated == true && 
            <h2>{initialState.user.name}</h2>
        }
        {/* <Link href="/user/1">User</Link> */}
        {sub_list != '' &&
        <table className='table table-bordered'>
            <thead>
              <tr>
                <td>ID</td>
                <td>Name</td>
                <td>Email</td>
                <td>State</td>
              </tr>
            </thead>
            <tbody>
              {sub_list}
            </tbody>
        </table>
        }
      </main>
    </div>
  )
}

// export async function getServerSideProps() {
//   const response = await http.get('subscribers').catch(error => { console.log(error)}); 
//   return {
//     props: {
//       subscribers:response?response.data.data:[]
//     }, // will be passed to the page component as props
//   }
// }